#!/usr/bin/env node
import {randomUUID} from 'node:crypto';
import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import * as z from 'zod/v4';
import {LibraryStore} from './library.mjs';
import {searchBatch} from './search-batch.mjs';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const server = new McpServer({name: 'innertune', version: '0.3.0'});
const store = new LibraryStore();
const found = new Map();
const reply = value => ({content: [{type: 'text', text: JSON.stringify(value, null, 2)}]});
const savedSummary = (data, queue) => ({id: queue.id, shortId: store.shortQueueId(queue.id), path: store.queuePath(data, queue), trackCount: queue.tracks.length, tracks: queue.tracks});
const summary = data => ({queueSource: {id: data.queueSourceId ?? null, name: data.queueSourceName || 'Current queue'}, playback: data.playback, queue: data.queue.map((track, index) => ({index, ...track})), folders: data.folders.map(folder => ({...folder, path: store.folderPath(data, folder.id)})), favorites: data.favorites, savedQueues: data.savedQueues.map(queue => savedSummary(data, queue))});
const resolve = (data, ids) => { const known = [...data.queue, ...data.favorites.map(x => x.track), ...data.savedQueues.flatMap(x => x.tracks)]; return ids.map(id => found.get(id) || known.find(x => x.id === id) || (() => { throw new Error(`Unknown video id ${id}; call search_songs first.`); })()); };
const markQueueEdited = data => { data.queueSourceId = null; data.queueSourceName = 'Current queue'; };
const ensureCurrent = data => {
  const current = data.playback?.track;
  if (current && !data.queue.some(track => track.id === current.id)) data.queue.unshift(current);
  return current;
};
const putNext = (data, tracks) => {
  const current = ensureCurrent(data);
  const currentId = current?.id || data.playback?.trackId;
  const requested = tracks.filter((track, index) =>
    track.id !== currentId && tracks.findIndex(item => item.id === track.id) === index);
  for (const track of requested) {
    const playingIndex = data.queue.findIndex(candidate => candidate.id === currentId);
    const existing = data.queue.findIndex((item, index) => item.id === track.id && index !== playingIndex);
    if (existing >= 0) data.queue.splice(existing, 1);
  }
  const currentIndex = data.queue.findIndex(track => track.id === currentId);
  data.queue.splice(currentIndex >= 0 ? currentIndex + 1 : 0, 0, ...requested);
  markQueueEdited(data);
  return requested;
};
const shuffledUnique = tracks => {
  const unique = [...new Map(tracks.filter(track => track?.id).map(track => [track.id, track])).values()];
  for (let index = unique.length - 1; index > 0; index--) {
    const other = Math.floor(Math.random() * (index + 1));
    [unique[index], unique[other]] = [unique[other], unique[index]];
  }
  return unique;
};
const uniqueTracks = tracks => [...new Map(tracks.filter(track => track?.id).map(track => [track.id, track])).values()];
async function runProvider(command, argument) { return new Promise((resolve, reject) => { const encoded = typeof argument === 'string' ? argument : JSON.stringify(argument); const child = spawn(process.execPath, [fileURLToPath(new URL('./provider.mjs', import.meta.url)), command, encoded], {stdio: ['ignore', 'pipe', 'pipe']}); let out = '', err = ''; child.stdout.on('data', x => out += x); child.stderr.on('data', x => err += x); child.on('close', code => code ? reject(new Error(err.trim() || `${command} failed.`)) : resolve(JSON.parse(out))); }); }
const search = query => runProvider('search', query);

server.registerTool('get_music_state', {description: 'Inspect the queue, folders, favorites, and saved queues.'}, async () => reply(summary(await store.read())));
server.registerTool('search_songs', {description: 'Run one or more YouTube Music searches concurrently. Put independent searches in the query array, then use returned video ids with the other tools.', inputSchema: {query: z.array(z.string().trim().min(1)).min(1).max(8), limit: z.number().int().min(1).max(30).default(10)}}, async ({query, limit}) => { const searches = await searchBatch(query, limit, search); searches.flatMap(result => result.tracks).forEach(track => found.set(track.id, track)); return reply({searches}); });
server.registerTool('get_artist_songs', {description: 'Open an artist catalog and return its songs. Use returned video ids with queue, favorite, or playback tools.', inputSchema: {name: z.string().trim().min(1), artistId: z.string().optional()}}, async ({name, artistId}) => { const detail = await runProvider('artist', {name, id: artistId}); detail.tracks.forEach(track => found.set(track.id, track)); return reply(detail); });
server.registerTool('play_song', {description: 'Play one song immediately as a standalone Playing now session. Use only when the user asks to play that song.', inputSchema: {videoId: z.string()}}, async ({videoId}) => { const before = await store.read(); const [track] = resolve(before, [videoId]); const data = await store.update(x => { x.queue = [track]; x.queueSourceId = null; x.queueSourceName = 'Playing now'; x.pendingCommands.push({id: randomUUID(), type: 'clear_play_next'}, {id: randomUUID(), type: 'play', index: 0}); }); return reply({playing: track, queueSource: data.queueSourceName}); });
server.registerTool('add_to_queue', {description: 'Append songs without starting or changing playback. If a standalone song is playing, it becomes the first song in the new ad-hoc queue.', inputSchema: {videoIds: z.array(z.string()).min(1)}}, async ({videoIds}) => { const before = await store.read(); const tracks = resolve(before, videoIds); const data = await store.update(x => { ensureCurrent(x); x.queue.push(...tracks); markQueueEdited(x); }); return reply({added: tracks, queueLength: data.queue.length}); });
server.registerTool('play_next', {description: 'Place songs directly after the current song and guarantee they play next, even when shuffle is on. This does not interrupt the current song.', inputSchema: {videoIds: z.array(z.string()).min(1)}}, async ({videoIds}) => { const before = await store.read(); const tracks = resolve(before, videoIds); let requested = []; const data = await store.update(x => { requested = putNext(x, tracks); for (const track of [...requested].reverse()) x.pendingCommands.push({id: randomUUID(), type: 'prioritize_next', trackId: track.id}); }); return reply({playNext: requested, queueLength: data.queue.length}); });
server.registerTool('replace_queue', {description: 'Replace the queue without changing playback.', inputSchema: {videoIds: z.array(z.string())}}, async ({videoIds}) => { const before = await store.read(); const tracks = resolve(before, videoIds); await store.update(x => { x.queue = tracks; markQueueEdited(x); x.pendingCommands.push({id: randomUUID(), type: 'clear_play_next'}); }); return reply({queue: tracks}); });
server.registerTool('remove_from_queue', {description: 'Remove zero-based queue indices without stopping playback.', inputSchema: {indices: z.array(z.number().int().min(0)).min(1)}}, async ({indices}) => reply(summary(await store.update(x => { x.queue = x.queue.filter((_, i) => !indices.includes(i)); markQueueEdited(x); }))));
server.registerTool('move_queue_song', {description: 'Move a song between zero-based queue positions.', inputSchema: {from: z.number().int().min(0), to: z.number().int().min(0)}}, async ({from, to}) => reply(summary(await store.update(x => { if (!x.queue[from]) throw new Error('Queue index does not exist.'); x.queue.splice(Math.max(0, Math.min(to, x.queue.length - 1)), 0, ...x.queue.splice(from, 1)); markQueueEdited(x); }))));
server.registerTool('clear_queue', {description: 'Clear the queue without stopping playback.'}, async () => reply(summary(await store.update(x => { x.queue = []; markQueueEdited(x); x.pendingCommands.push({id: randomUUID(), type: 'clear_play_next'}); }))));
server.registerTool('create_folder', {description: 'Create a nested library folder path.', inputSchema: {path: z.string().min(1)}}, async ({path}) => { let folder; const data = await store.update(x => folder = store.ensureFolder(x, path)); return reply({folder, path: store.folderPath(data, folder.id)}); });
server.registerTool('save_current_queue', {description: 'Create a saved playlist from the current queue, or update the playlist already at the exact path. Prefer update_saved_queue with a short ID when the user means an existing playlist.', inputSchema: {path: z.string().min(1)}}, async ({path}) => { let saved; const data = await store.update(x => { const parts = path.split(/[\\/]+/).filter(Boolean), name = parts.pop(); const folder = parts.length ? store.ensureFolder(x, parts.join('/')) : undefined; saved = x.savedQueues.find(q => q.name.toLowerCase() === name.toLowerCase() && q.folderId === (folder?.id ?? null)); if (saved) { saved.tracks = [...x.queue]; saved.updatedAt = new Date().toISOString(); } else { saved = {id: randomUUID(), name, folderId: folder?.id ?? null, tracks: [...x.queue], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString()}; x.savedQueues.push(saved); } }); return reply(savedSummary(data, saved)); });
server.registerTool('update_saved_queue', {description: 'Update an existing saved playlist by the shortId returned by get_music_state. Omit videoIds to use the current queue. Mode replace overwrites its songs, append adds unique songs, and remove deletes the given songs. This never starts playback.', inputSchema: {shortId: z.string().trim().min(1), videoIds: z.array(z.string()).optional(), mode: z.enum(['replace','append','remove']).default('replace'), name: z.string().trim().min(1).optional(), folderPath: z.string().trim().optional()}}, async ({shortId, videoIds, mode, name, folderPath}) => { if (mode === 'remove' && videoIds === undefined) throw new Error('remove requires videoIds.'); const before = await store.read(), selected = store.findQueue(before, shortId); const tracks = videoIds === undefined ? [...before.queue] : resolve(before, videoIds); let updated; const data = await store.update(x => { updated = store.findQueue(x, selected.id); if (mode === 'replace') updated.tracks = [...tracks]; else if (mode === 'append') updated.tracks = uniqueTracks([...updated.tracks, ...tracks]); else { const removed = new Set(tracks.map(track => track.id)); updated.tracks = updated.tracks.filter(track => !removed.has(track.id)); } if (name) updated.name = name; if (folderPath !== undefined) updated.folderId = folderPath ? store.ensureFolder(x, folderPath).id : null; updated.updatedAt = new Date().toISOString(); if (x.queueSourceId === updated.id) { const matchesCurrent = mode === 'replace' && videoIds === undefined && x.queue.length === updated.tracks.length && x.queue.every((track, index) => track.id === updated.tracks[index]?.id); if (matchesCurrent) x.queueSourceName = store.queuePath(x, updated); else markQueueEdited(x); } }); return reply({...savedSummary(data, updated), mode}); });
server.registerTool('load_saved_queue', {description: 'Load a saved queue by short ID, full ID, or path without changing playback.', inputSchema: {idOrPath: z.string().min(1)}}, async ({idOrPath}) => { const before = await store.read(), saved = store.findQueue(before, idOrPath), path = store.queuePath(before, saved); await store.update(x => { x.queue = [...saved.tracks]; x.queueSourceId = saved.id; x.queueSourceName = path; x.pendingCommands.push({id: randomUUID(), type: 'clear_play_next'}); }); return reply({loaded: path, id: saved.id, shortId: store.shortQueueId(saved.id)}); });
server.registerTool('shuffle_all_saved_queues', {description: 'Combine every saved queue, deduplicate songs, shuffle the entire set, and start playing it. Use only when the user explicitly asks to shuffle all saved queues.', inputSchema: {}}, async () => { let tracks = []; const data = await store.update(x => { tracks = shuffledUnique(x.savedQueues.flatMap(queue => queue.tracks)); if (tracks.length === 0) throw new Error('There are no songs in saved queues.'); x.queue = tracks; x.queueSourceId = null; x.queueSourceName = 'All queues · shuffled'; x.pendingCommands.push({id: randomUUID(), type: 'clear_play_next'}, {id: randomUUID(), type: 'play', index: 0}); }); return reply({playing: data.queue[0], queueLength: tracks.length, queueSource: data.queueSourceName}); });
server.registerTool('delete_saved_queue', {description: 'Delete a saved queue by short ID or full ID.', inputSchema: {id: z.string()}}, async ({id}) => { const before = await store.read(), selected = store.findQueue(before, id); return reply(summary(await store.update(x => { x.savedQueues = x.savedQueues.filter(q => q.id !== selected.id); if (x.queueSourceId === selected.id) markQueueEdited(x); }))); });
server.registerTool('favorite_songs', {description: 'Favorite songs, optionally in a folder path.', inputSchema: {videoIds: z.array(z.string()).min(1), folderPath: z.string().optional()}}, async ({videoIds, folderPath}) => { const before = await store.read(), tracks = resolve(before, videoIds); return reply(summary(await store.update(x => { const folder = folderPath ? store.ensureFolder(x, folderPath) : undefined; for (const track of tracks) { const existing = x.favorites.find(f => f.track.id === track.id); if (existing) existing.folderId = folder?.id ?? existing.folderId; else x.favorites.push({track, folderId: folder?.id ?? null, addedAt: new Date().toISOString()}); } }))); });
server.registerTool('unfavorite_songs', {description: 'Remove favorites by video id.', inputSchema: {videoIds: z.array(z.string()).min(1)}}, async ({videoIds}) => reply(summary(await store.update(x => x.favorites = x.favorites.filter(f => !videoIds.includes(f.track.id))))));
server.registerTool('control_playback', {description: 'Control playback only when the user explicitly requests it. Can also set shuffle/repeat or open and close the current song video.', inputSchema: {action: z.enum(['play','pause','resume','toggle','next','previous','seek','volume','shuffle','repeat','watch_video','close_video']), index: z.number().int().min(0).optional(), seconds: z.number().optional(), volume: z.number().min(0).max(100).optional(), enabled: z.boolean().optional(), repeatMode: z.enum(['off','all','one']).optional()}}, async args => { const command = {id: randomUUID(), type: args.action}; if (args.action === 'play') { if (args.index === undefined) throw new Error('play requires index.'); command.index = args.index; } if (args.action === 'seek') command.seconds = args.seconds; if (args.action === 'volume') command.value = args.volume; if (args.action === 'shuffle') { if (args.enabled === undefined) throw new Error('shuffle requires enabled.'); command.enabled = args.enabled; } if (args.action === 'repeat') { if (!args.repeatMode) throw new Error('repeat requires repeatMode.'); command.mode = args.repeatMode; } await store.update(x => x.pendingCommands.push(command)); return reply({queuedPlaybackAction: args.action}); });

await server.connect(new StdioServerTransport());
