#!/usr/bin/env node
import {randomUUID} from 'node:crypto';
import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import * as z from 'zod/v4';
import {LibraryStore} from './library.mjs';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const server = new McpServer({name: 'innertune', version: '0.1.0'});
const store = new LibraryStore();
const found = new Map();
const reply = value => ({content: [{type: 'text', text: JSON.stringify(value, null, 2)}]});
const summary = data => ({queueSource: {id: data.queueSourceId ?? null, name: data.queueSourceName || 'Current queue'}, playback: data.playback, queue: data.queue.map((track, index) => ({index, ...track})), folders: data.folders.map(folder => ({...folder, path: store.folderPath(data, folder.id)})), favorites: data.favorites, savedQueues: data.savedQueues.map(queue => ({id: queue.id, path: store.queuePath(data, queue), trackCount: queue.tracks.length, tracks: queue.tracks}))});
const resolve = (data, ids) => { const known = [...data.queue, ...data.favorites.map(x => x.track), ...data.savedQueues.flatMap(x => x.tracks)]; return ids.map(id => found.get(id) || known.find(x => x.id === id) || (() => { throw new Error(`Unknown video id ${id}; call search_songs first.`); })()); };
const markQueueEdited = data => { data.queueSourceId = null; data.queueSourceName = 'Current queue'; };
async function search(query) { return new Promise((resolve, reject) => { const child = spawn(process.execPath, [fileURLToPath(new URL('./provider.mjs', import.meta.url)), 'search', query], {stdio: ['ignore', 'pipe', 'pipe']}); let out = '', err = ''; child.stdout.on('data', x => out += x); child.stderr.on('data', x => err += x); child.on('close', code => code ? reject(new Error(err.trim() || 'Search failed.')) : resolve(JSON.parse(out))); }); }

server.registerTool('get_music_state', {description: 'Inspect the queue, folders, favorites, and saved queues.'}, async () => reply(summary(await store.read())));
server.registerTool('search_songs', {description: 'Search YouTube Music. Use video ids with the other tools.', inputSchema: {query: z.string().min(1), limit: z.number().int().min(1).max(30).default(10)}}, async ({query, limit}) => { const tracks = (await search(query)).slice(0, limit); tracks.forEach(x => found.set(x.id, x)); return reply({query, tracks}); });
server.registerTool('add_to_queue', {description: 'Append songs without starting or changing playback.', inputSchema: {videoIds: z.array(z.string()).min(1)}}, async ({videoIds}) => { const before = await store.read(); const tracks = resolve(before, videoIds); const data = await store.update(x => { x.queue.push(...tracks); markQueueEdited(x); }); return reply({added: tracks, queueLength: data.queue.length}); });
server.registerTool('replace_queue', {description: 'Replace the queue without changing playback.', inputSchema: {videoIds: z.array(z.string())}}, async ({videoIds}) => { const before = await store.read(); const tracks = resolve(before, videoIds); await store.update(x => { x.queue = tracks; markQueueEdited(x); }); return reply({queue: tracks}); });
server.registerTool('remove_from_queue', {description: 'Remove zero-based queue indices without stopping playback.', inputSchema: {indices: z.array(z.number().int().min(0)).min(1)}}, async ({indices}) => reply(summary(await store.update(x => { x.queue = x.queue.filter((_, i) => !indices.includes(i)); markQueueEdited(x); }))));
server.registerTool('move_queue_song', {description: 'Move a song between zero-based queue positions.', inputSchema: {from: z.number().int().min(0), to: z.number().int().min(0)}}, async ({from, to}) => reply(summary(await store.update(x => { if (!x.queue[from]) throw new Error('Queue index does not exist.'); x.queue.splice(Math.max(0, Math.min(to, x.queue.length - 1)), 0, ...x.queue.splice(from, 1)); markQueueEdited(x); }))));
server.registerTool('clear_queue', {description: 'Clear the queue without stopping playback.'}, async () => reply(summary(await store.update(x => { x.queue = []; markQueueEdited(x); }))));
server.registerTool('create_folder', {description: 'Create a nested library folder path.', inputSchema: {path: z.string().min(1)}}, async ({path}) => { let folder; const data = await store.update(x => folder = store.ensureFolder(x, path)); return reply({folder, path: store.folderPath(data, folder.id)}); });
server.registerTool('save_current_queue', {description: 'Save the current queue at a name or folder/name path.', inputSchema: {path: z.string().min(1)}}, async ({path}) => { let saved; const data = await store.update(x => { const parts = path.split(/[\\/]+/).filter(Boolean), name = parts.pop(); const folder = parts.length ? store.ensureFolder(x, parts.join('/')) : undefined; saved = x.savedQueues.find(q => q.name.toLowerCase() === name.toLowerCase() && q.folderId === (folder?.id ?? null)); if (saved) { saved.tracks = [...x.queue]; saved.updatedAt = new Date().toISOString(); } else { saved = {id: randomUUID(), name, folderId: folder?.id ?? null, tracks: [...x.queue], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString()}; x.savedQueues.push(saved); } }); return reply({path: store.queuePath(data, saved), trackCount: saved.tracks.length}); });
server.registerTool('load_saved_queue', {description: 'Load a saved queue without changing playback.', inputSchema: {idOrPath: z.string().min(1)}}, async ({idOrPath}) => { const before = await store.read(), saved = store.findQueue(before, idOrPath), path = store.queuePath(before, saved); await store.update(x => { x.queue = [...saved.tracks]; x.queueSourceId = saved.id; x.queueSourceName = path; }); return reply({loaded: path}); });
server.registerTool('delete_saved_queue', {description: 'Delete a saved queue by id.', inputSchema: {id: z.string()}}, async ({id}) => reply(summary(await store.update(x => { x.savedQueues = x.savedQueues.filter(q => q.id !== id); if (x.queueSourceId === id) markQueueEdited(x); }))));
server.registerTool('favorite_songs', {description: 'Favorite songs, optionally in a folder path.', inputSchema: {videoIds: z.array(z.string()).min(1), folderPath: z.string().optional()}}, async ({videoIds, folderPath}) => { const before = await store.read(), tracks = resolve(before, videoIds); return reply(summary(await store.update(x => { const folder = folderPath ? store.ensureFolder(x, folderPath) : undefined; for (const track of tracks) { const existing = x.favorites.find(f => f.track.id === track.id); if (existing) existing.folderId = folder?.id ?? existing.folderId; else x.favorites.push({track, folderId: folder?.id ?? null, addedAt: new Date().toISOString()}); } }))); });
server.registerTool('unfavorite_songs', {description: 'Remove favorites by video id.', inputSchema: {videoIds: z.array(z.string()).min(1)}}, async ({videoIds}) => reply(summary(await store.update(x => x.favorites = x.favorites.filter(f => !videoIds.includes(f.track.id))))));
server.registerTool('control_playback', {description: 'Control playback only when the user explicitly requests it. Can also set shuffle/repeat or open and close the current song video.', inputSchema: {action: z.enum(['play','pause','resume','toggle','next','previous','seek','volume','shuffle','repeat','watch_video','close_video']), index: z.number().int().min(0).optional(), seconds: z.number().optional(), volume: z.number().min(0).max(100).optional(), enabled: z.boolean().optional(), repeatMode: z.enum(['off','all','one']).optional()}}, async args => { const command = {id: randomUUID(), type: args.action}; if (args.action === 'play') { if (args.index === undefined) throw new Error('play requires index.'); command.index = args.index; } if (args.action === 'seek') command.seconds = args.seconds; if (args.action === 'volume') command.value = args.volume; if (args.action === 'shuffle') { if (args.enabled === undefined) throw new Error('shuffle requires enabled.'); command.enabled = args.enabled; } if (args.action === 'repeat') { if (!args.repeatMode) throw new Error('repeat requires repeatMode.'); command.mode = args.repeatMode; } await store.update(x => x.pendingCommands.push(command)); return reply({queuedPlaybackAction: args.action}); });

await server.connect(new StdioServerTransport());
